package com.grupo10.asistenteingesta.util;

public enum Constante {
    EMAIL,
    INGESTA,
    TIPO_INGESTA,
    MEDICAMENTO,
    BEBIDA,
    TIEMPO_RESTANTE_MEDICAMENTO,
    TIEMPO_RESTANTE_BEBIDA,
    RECEIVER_TIEMPO_RESTANTE,
    TIPO_EVENTO_ALARMA_REGISTRADA,
    LLAMADO_INICIAL,
    LLAMADO_POST_ACTUALIZACION_TOKEN
}
